///
/// Copyright © 2024 DQOps (support@dqops.com)
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

export enum CONNECTION_ACTION {
  GET_CONNECTIONS = 'CONNECTION_ACTION/GET_CONNECTIONS',
  GET_CONNECTIONS_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTIONS_SUCCESS',
  GET_CONNECTIONS_ERROR = 'CONNECTION_ACTION/GET_CONNECTIONS_ERROR',
  SET_ACTIVE_CONNECTION = 'SET_ACTIVE_CONNECTION',
  GET_CONNECTION_BASIC = 'CONNECTION_ACTION/GET_CONNECTION_BASIC',
  GET_CONNECTION_BASIC_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTION_BASIC_SUCCESS',
  GET_CONNECTION_BASIC_ERROR = 'CONNECTION_ACTION/GET_CONNECTION_BASIC_ERROR',
  UPDATE_CONNECTION_BASIC = 'CONNECTION_ACTION/UPDATE_CONNECTION_BASIC',
  UPDATE_CONNECTION_BASIC_SUCCESS = 'CONNECTION_ACTION/UPDATE_CONNECTION_BASIC_SUCCESS',
  UPDATE_CONNECTION_BASIC_ERROR = 'CONNECTION_ACTION/UPDATE_CONNECTION_BASIC_ERROR',
  RESET_CONNECTION_SCHEDULE_GROUP = 'CONNECTION_ACTION/RESET_CONNECTION_SCHEDULE_GROUP',
  GET_CONNECTION_SCHEDULE_GROUP = 'CONNECTION_ACTION/GET_CONNECTION_SCHEDULE_GROUP',
  GET_CONNECTION_SCHEDULE_GROUP_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTION_SCHEDULE_GROUP_SUCCESS',
  GET_CONNECTION_SCHEDULE_GROUP_ERROR = 'CONNECTION_ACTION/GET_CONNECTION_SCHEDULE_GROUP_ERROR',
  UPDATE_CONNECTION_SCHEDULE_GROUP = 'CONNECTION_ACTION/UPDATE_CONNECTION_SCHEDULE_GROUP',
  UPDATE_CONNECTION_SCHEDULE_GROUP_SUCCESS = 'CONNECTION_ACTION/UPDATE_CONNECTION_SCHEDULE_GROUP_SUCCESS',
  UPDATE_CONNECTION_SCHEDULE_GROUP_ERROR = 'CONNECTION_ACTION/UPDATE_CONNECTION_SCHEDULE_GROUP_ERROR',
  GET_CONNECTION_COMMENTS = 'CONNECTION_ACTION/GET_CONNECTION_COMMENTS',
  GET_CONNECTION_COMMENTS_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTION_COMMENTS_SUCCESS',
  GET_CONNECTION_COMMENTS_ERROR = 'CONNECTION_ACTION/GET_CONNECTION_COMMENTS_ERROR',
  UPDATE_CONNECTION_COMMENTS = 'CONNECTION_ACTION/UPDATE_CONNECTION_COMMENTS',
  UPDATE_CONNECTION_COMMENTS_SUCCESS = 'CONNECTION_ACTION/UPDATE_CONNECTION_COMMENTS_SUCCESS',
  UPDATE_CONNECTION_COMMENTS_ERROR = 'CONNECTION_ACTION/UPDATE_CONNECTION_COMMENTS_ERROR',
  GET_CONNECTION_LABELS = 'CONNECTION_ACTION/GET_CONNECTION_LABELS',
  GET_CONNECTION_LABELS_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTION_LABELS_SUCCESS',
  GET_CONNECTION_LABELS_ERROR = 'CONNECTION_ACTION/GET_CONNECTION_LABELS_ERROR',
  UPDATE_CONNECTION_LABELS = 'CONNECTION_ACTION/UPDATE_CONNECTION_LABELS',
  UPDATE_CONNECTION_LABELS_SUCCESS = 'CONNECTION_ACTION/UPDATE_CONNECTION_LABELS_SUCCESS',
  UPDATE_CONNECTION_LABELS_ERROR = 'CONNECTION_ACTION/UPDATE_CONNECTION_LABELS_ERROR',
  GET_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION = 'CONNECTION_ACTION/GET_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION',
  GET_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_SUCCESS',
  GET_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_ERROR = 'CONNECTION_ACTION/GET_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_ERROR',
  UPDATE_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION = 'CONNECTION_ACTION/UPDATE_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION',
  UPDATE_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_SUCCESS = 'CONNECTION_ACTION/UPDATE_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_SUCCESS',
  UPDATE_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATION_ERROR = 'CONNECTION_ACTION/UPDATE_CONNECTION_DEFAULT_DATA_GROUPING_CONFIGURATIONG_ERROR',
  SET_UPDATED_CONNECTION_BASIC = 'CONNECTION_ACTION/SET_UPDATED_CONNECTION_BASIC',
  SET_IS_UPDATED_CONNECTION_BASIC = 'CONNECTION_ACTION/SET_IS_UPDATED_CONNECTION_BASIC',
  SET_UPDATED_SCHEDULE = 'CONNECTION_ACTION/SET_UPDATED_SCHEDULE',
  SET_IS_UPDATED_SCHEDULE = 'CONNECTION_ACTION/SET_IS_UPDATED_SCHEDULE',
  SET_UPDATED_SCHEDULE_GROUP = 'CONNECTION_ACTION/SET_UPDATED_SCHEDULE_GROUP',
  SET_IS_UPDATED_SCHEDULE_GROUP = 'CONNECTION_ACTION/SET_IS_UPDATED_SCHEDULE_GROUP',
  SET_UPDATED_COMMENTS = 'CONNECTION_ACTION/SET_UPDATED_COMMENTS',
  SET_IS_UPDATED_COMMENTS = 'CONNECTION_ACTION/SET_IS_UPDATED_COMMENTS',
  SET_UPDATED_LABELS = 'CONNECTION_ACTION/SET_UPDATED_LABELS',
  SET_IS_UPDATED_LABELS = 'CONNECTION_ACTION/SET_IS_UPDATED_LABELS',
  SET_UPDATED_DATA_GROUPING_CONFIGURATION = 'CONNECTION_ACTION/SET_UPDATED_DATA_GROUPING_CONFIGURATION',
  SET_IS_UPDATED_DATA_GROUPING_CONFIGURATION = 'CONNECTION_ACTION/SET_IS_UPDATED_DATA_GROUPING_CONFIGURATION',
}
