export enum DATA_QUALITY_CHECKS_ACTION {
  GET_DATA_QUALITY_CHECKS_FOLDER_TREE = 'DATA_QUALITY_CHECKS_ACTION/GET_DATA_QUALITY_CHECKS_FOLDER_TREE',
  GET_DATA_QUALITY_CHECKS_FOLDER_TREE_SUCCESS = 'DATA_QUALITY_CHECKS_ACTION/GET_DATA_QUALITY_CHECKS_FOLDER_TREE_SUCCESS',
  GET_DATA_QUALITY_CHECKS_FOLDER_TREE_ERROR = 'DATA_QUALITY_CHECKS_ACTION/GET_DATA_QUALITY_CHECKS_FOLDER_TREE_ERROR',
  TOGGLE_DATA_QUALITY_CHECKS_FOLDER = 'DATA_QUALITY_CHECKS_ACTION/TOGGLE_DATA_QUALITY_CHECKS_FOLDER',
  UPDATE_DATA_QUALITY_CHECKS_FOLDER_TREE = 'DATA_QUALITY_CHECKS_ACTION/UPDATE_DATA_QUALITY_CHECKS_FOLDER_TREE',

  CREATE_CHECK_DETAIL = 'DATA_QUALITY_CHECKS_ACTION/CREATE_CHECK_DETAIL',
  UPDATE_CHECK_DETAIL = 'DATA_QUALITY_CHECKS_ACTION/UPDATE_CHECK_DETAIL',
  DELETE_CHECK_DETAIL = 'DATA_QUALITY_CHECKS_ACTION/DELETE_CHECK_DETAIL',

  ADD_FIRST_LEVEL_TAB = 'DATA_QUALITY_CHECKS_ACTION/ADD_FIRST_LEVEL_TAB',
  SET_ACTIVE_FIRST_LEVEL_TAB = 'DATA_QUALITY_CHECKS_ACTION/SET_ACTIVE_FIRST_LEVEL_TAB',
  CLOSE_FIRST_LEVEL_TAB = 'DATA_QUALITY_CHECKS_ACTION/CLOSE_FIRST_LEVEL_TAB',

  GET_CHECK_DETAIL = 'DATA_QUALITY_CHECKS_ACTION/GET_CHECK_DETAIL',
  GET_CHECK_DETAIL_SUCCESS = 'DATA_QUALITY_CHECKS_ACTION/GET_CHECK_DETAIL_SUCCESS'
}
