
export enum DATA_QUALITY_CHECKS_ACTION {
    GET_DATA_QUALITY_CHECKS_FOLDER_TREE = 'DATA_QUALITY_CHECKS_ACTION/GET_DATA_QUALITY_CHECKS_FOLDER_TREE',
    GET_DATA_QUALITY_CHECKS_FOLDER_TREE_SUCCESS = 'DATA_QUALITY_CHECKS_ACTION/GET_DATA_QUALITY_CHECKS_FOLDER_TREE_SUCCESS',
    GET_DATA_QUALITY_CHECKS_FOLDER_TREE_ERROR = 'DATA_QUALITY_CHECKS_ACTION/GET_DATA_QUALITY_CHECKS_FOLDER_TREE_ERROR',
    TOGGLE_DATA_QUALITY_CHECKS_FOLDER = 'DATA_QUALITY_CHECKS_ACTION/TOGGLE_DATA_QUALITY_CHECKS_FOLDER',
    UPDATE_DATA_QUALITY_CHECKS_FOLDER_TREE = 'DATA_QUALITY_CHECKS_ACTION/UPDATE_DATA_QUALITY_CHECKS_FOLDER_TREE',
  }