///
/// Copyright © 2024 DQOps (support@dqops.com)
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

export enum SENSOR_ACTION {
  GET_SENSOR_FOLDER_TREE = 'SENSOR_ACTION/GET_SENSOR_FOLDER_TREE',
  GET_SENSOR_FOLDER_TREE_SUCCESS = 'SENSOR_ACTION/GET_SENSOR_FOLDER_TREE_SUCCESS',
  GET_SENSOR_FOLDER_TREE_ERROR = 'SENSOR_ACTION/GET_SENSOR_FOLDER_TREE_ERROR',

  UPDATE_SENSOR_FOLDER_TREE = 'SENSOR_ACTION/UPDATE_SENSOR_FOLDER_TREE',
  TOGGLE_SENSOR_FOLDER = 'SENSOR_ACTION/TOGGLE_SENSOR_FOLDER',
  ADD_FIRST_LEVEL_TAB = 'SENSOR_ACTION/ADD_FIRST_LEVEL_TAB',
  SET_ACTIVE_FIRST_LEVEL_TAB = 'SENSOR_ACTION/SET_ACTIVE_FIRST_LEVEL_TAB',
  CLOSE_FIRST_LEVEL_TAB = 'SENSOR_ACTION/CLOSE_FIRST_LEVEL_TAB',
  GET_SENSOR_DETAIL = 'SENSOR_ACTION/GET_SENSOR_DETAIL',
  GET_SENSOR_DETAIL_SUCCESS = 'SENSOR_ACTION/GET_SENSOR_DETAIL_SUCCESS',
  GET_SENSOR_DETAIL_FAILED = 'SENSOR_ACTION/GET_SENSOR_DETAIL_FAILED',
  GET_RULE_DETAIL = 'SENSOR_ACTION/GET_RULE_DETAIL',
  GET_RULE_DETAIL_SUCCESS = 'SENSOR_ACTION/GET_RULE_DETAIL_SUCCESS',
  GET_RULE_DETAIL_FAILED = 'SENSOR_ACTION/GET_RULE_DETAIL_FAILED',

  SET_UPDATED_RULE = 'SENSOR_ACTION/SET_UPDATED_RULE',
  SET_UPDATED_SENSOR = 'SENSOR_ACTION/SET_UPDATED_SENSOR',

  UPDATE_SENSOR_DETAIL = 'SENSOR_ACTION/UPDATE_SENSOR_DETAIL',
  UPDATE_SENSOR_DETAIL_SUCCESS = 'SENSOR_ACTION/UPDATE_SENSOR_DETAIL_SUCCESS',
  UPDATE_SENSOR_DETAIL_FAILED = 'SENSOR_ACTION/UPDATE_SENSOR_DETAIL_FAILED',

  UPDATE_RULE_DETAIL = 'SENSOR_ACTION/UPDATE_RULE_DETAIL',
  UPDATE_RULE_DETAIL_SUCCESS = 'SENSOR_ACTION/UPDATE_RULE_DETAIL_SUCCESS',
  UPDATE_RULE_DETAIL_FAILED = 'SENSOR_ACTION/UPDATE_RULE_DETAIL_FAILED',

  CREATE_RULE_DETAIL = 'SENSOR_ACTION/CREATE_RULE_DETAIL',
  CREATE_RULE_DETAIL_SUCCESS = 'SENSOR_ACTION/CREATE_RULE_DETAIL_SUCCESS',
  CREATE_RULE_DETAIL_FAILED = 'SENSOR_ACTION/CREATE_RULE_DETAIL_FAILED',

  CREATE_SENSOR_DETAIL = 'SENSOR_ACTION/CREATE_SENSOR_DETAIL',
  CREATE_SENSOR_DETAIL_SUCCESS = 'SENSOR_ACTION/CREATE_SENSOR_DETAIL_SUCCESS',
  CREATE_SENSOR_DETAIL_FAILED = 'SENSOR_ACTION/CREATE_SENSOR_DETAIL_FAILED',
}
