FROM openjdk:17-jdk-slim-buster AS dqo-libs
RUN apt-get update && apt-get install -y unzip

WORKDIR /workspace/app
COPY ./distribution/target/ /workspace/app/temp/
COPY VERSION /workspace/app/temp/
RUN unzip /workspace/app/temp/dqo-distribution-$(cat /workspace/app/temp/VERSION)-bin.zip -d /workspace/app/home
WORKDIR /workspace/app/home
RUN mkdir -p /workspace/app/home/expanded && (cd expanded; jar -xf ../jars/dqo-dqops-$(cat /workspace/app/temp/VERSION).jar) && rm /workspace/app/home/jars/dqo-dqops-$(cat /workspace/app/temp/VERSION).jar

FROM python:3.12.0-slim-bookworm AS dqo-home
WORKDIR /dqo

# copy dqo home
COPY home home
WORKDIR /dqo/home
RUN rm -rf venv/ && rm lib/requirements_dev.txt

# recreate venv
ENV VIRTUAL_ENV=/dqo/home/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY home/lib/requirements.txt /dqo/home/venv/home_requirements.txt
RUN python3 -m pip install setuptools && python3 -m pip install -r $VIRTUAL_ENV/home_requirements.txt

RUN python3 -m compileall ./

FROM python:3.12.0-slim-bookworm AS dqo-main
EXPOSE 8888
WORKDIR /dqo

# install java
RUN apt-get update && apt-get install -y openjdk-17-jre-headless && apt-get clean
ARG TARGETARCH=amd64
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-$TARGETARCH
ENV PATH=$JAVA_HOME/bin:$PATH

# dqo launch setup
ENV DQO_HOME=/dqo/home
ENV DQO_USER_HOME=/dqo/userhome
ENV DQO_USER_INITIALIZE_USER_HOME=true
ENV DQO_USER_INITIALIZE_DEFAULT_CLOUD_CREDENTIALS=true
ENV DQO_LOGGING_CONSOLE_IMMEDIATE_FLUSH=true
ENV AZURE_ENABLE_HTTP_CLIENT_SHARING=true
RUN mkdir $DQO_USER_HOME
RUN touch $DQO_USER_HOME/.DQO_USER_HOME_NOT_MOUNTED
COPY --from=dqo-home /dqo/home home

COPY distribution/dqo_docker_entrypoint.sh /dqo/home/bin/
RUN chmod +x /dqo/home/bin/dqo_docker_entrypoint.sh

# copy spring dependencies
ARG DEPENDENCY=/workspace/app/home
COPY --from=dqo-libs ${DEPENDENCY}/jars /dqo/app/lib
COPY --from=dqo-libs ${DEPENDENCY}/expanded/BOOT-INF/lib /dqo/app/lib
COPY --from=dqo-libs ${DEPENDENCY}/expanded/META-INF /dqo/app/META-INF
COPY --from=dqo-libs ${DEPENDENCY}/expanded/BOOT-INF/classes /dqo/app
ENTRYPOINT ["/dqo/home/bin/dqo_docker_entrypoint.sh"]
