FROM openjdk:17-jdk-slim-buster AS dqo-libs
RUN apt-get update && apt-get install -y unzip

WORKDIR /workspace/app
COPY ./distribution/target/ /workspace/app/temp/
COPY VERSION /workspace/app/temp/
RUN unzip /workspace/app/temp/dqo-distribution-$(cat /workspace/app/temp/VERSION)-bin.zip -d /workspace/app/home
WORKDIR /workspace/app/home
RUN mkdir -p /workspace/app/home/expanded && (cd expanded; jar -xf ../jars/dqo-dqops-$(cat /workspace/app/temp/VERSION).jar) && rm /workspace/app/home/jars/dqo-dqops-$(cat /workspace/app/temp/VERSION).jar

FROM python:3.11.3-slim-bullseye AS dqo-home
WORKDIR /dqo

# copy dqo home
COPY home home
WORKDIR /dqo/home
RUN rm -rf venv/

# recreate venv
ENV VIRTUAL_ENV=/dqo/home/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN cp lib/requirements.txt $VIRTUAL_ENV/home_requirements.txt
RUN pip3 install -r $VIRTUAL_ENV/home_requirements.txt

RUN python3 -m compileall ./

FROM python:3.11.3-slim-bullseye AS dqo-main
EXPOSE 8888
WORKDIR /dqo

# install java
RUN apt-get update && apt-get install -y openjdk-17-jre-headless && apt-get clean
ARG TARGETARCH=amd64
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-$TARGETARCH
ENV PATH=$JAVA_HOME/bin:$PATH

# dqo launch setup
ENV DQO_HOME=/dqo/home
ENV DQO_USER_HOME=/dqo/userhome
ENV DQO_USER_INITIALIZE_USER_HOME=true
ENV DQO_PYTHON_USE_HOST_PYTHON=true
ENV DQO_LOGGING_CONSOLE_IMMEDIATE_FLUSH=true
RUN mkdir $DQO_USER_HOME
RUN touch $DQO_USER_HOME/.DQO_USER_HOME_NOT_MOUNTED
COPY --from=dqo-home /dqo/home home

# copy spring dependencies
ARG DEPENDENCY=/workspace/app/home
COPY --from=dqo-libs ${DEPENDENCY}/jars /dqo/app/lib
COPY --from=dqo-libs ${DEPENDENCY}/expanded/BOOT-INF/lib /dqo/app/lib
COPY --from=dqo-libs ${DEPENDENCY}/expanded/META-INF /dqo/app/META-INF
COPY --from=dqo-libs ${DEPENDENCY}/expanded/BOOT-INF/classes /dqo/app
ENV JAVA_TOOL_OPTIONS="-Xmx1024m"
ENTRYPOINT ["java", "-cp", "/dqo/app:/dqo/app/lib/*", "com.dqops.cli.CliApplication"]
