#!/bin/bash
#
# Copyright © 2021-Present DQOps, Documati sp. z o.o. (support@dqops.com)
#
# This file is licensed under the Business Source License 1.1,
# which can be found in the root directory of this repository.
#
# Change Date: This file will be licensed under the Apache License, Version 2.0,
# four (4) years from its last modification date.
#

export DQO_VERSION=1.11.7

# Configure local development environment overrides
if [ -f $(dirname $0)/set-dqo-envs.sh ]; then
    . $(dirname $0)/set-dqo-envs.sh

    returnedValue=$?
    if [ $returnedValue -ne 0 ]; then
        echo "DQOps cannot be started"
        exit $returnedValue
    fi
fi

# Figure out where DQO is installed
. $(dirname $0)/find-dqo-home.sh
returnedValue=$?
if [ $returnedValue -ne 0 ]; then
    echo "DQOps cannot be started"
    exit $returnedValue
fi

# Configure class paths
. $(dirname $0)/find-dqo-classpath.sh

returnedValue=$?
if [ $returnedValue -ne 0 ]; then
    echo "DQOps cannot be started"
    exit $returnedValue
fi

$DQO_RUNNER $DQO_JAVA_OPTS --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED -cp "$DQO_LAUNCH_CLASSPATH" com.dqops.cli.CliApplication $*