#!/bin/bash
#
# Copyright © 2021-2024 DQOps (support@dqops.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export DQO_VERSION=1.2.0

# Configure local development environment overrides
if [ -f $(dirname $0)/set-dqo-envs.sh ]; then
    . $(dirname $0)/set-dqo-envs.sh

    returnedValue=$?
    if [ $returnedValue -ne 0 ]; then
        echo "DQOps cannot be started"
        exit $returnedValue
    fi
fi

# Figure out where DQO is installed
. $(dirname $0)/find-dqo-home.sh
returnedValue=$?
if [ $returnedValue -ne 0 ]; then
    echo "DQOps cannot be started"
    exit $returnedValue
fi

# Configure class paths
. $(dirname $0)/find-dqo-classpath.sh

returnedValue=$?
if [ $returnedValue -ne 0 ]; then
    echo "DQOps cannot be started"
    exit $returnedValue
fi

$DQO_RUNNER $DQO_JAVA_OPTS --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED -cp "$DQO_LAUNCH_CLASSPATH" org.springframework.boot.loader.JarLauncher $*