export enum AUTH_ACTION {
  FETCH_CURRENT_USER = 'AUTH_ACTION/FETCH_CURRENT_USER',
  FETCH_CURRENT_USER_SUCCESS = 'AUTH_ACTION/FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_ERROR = 'AUTH_ACTION/FETCH_CURRENT_USER_ERROR',
  LOGIN_REQUEST = 'AUTH_ACTION/LOGIN_REQUEST',
  LOGIN_SUCCESS = 'AUTH_ACTION/LOGIN_SUCCESS',
  LOGIN_ERROR = 'AUTH_ACTION/LOGIN_ERROR',
}
