///
/// Copyright © 2021 DQO.ai (support@dqo.ai)
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

export enum COLUMN_ACTION {
  GET_COLUMNS = 'COLUMN_ACTION/GET_COLUMNS',
  GET_COLUMNS_SUCCESS = 'COLUMN_ACTION/GET_COLUMNS_SUCCESS',
  GET_COLUMNS_ERROR = 'COLUMN_ACTION/GET_COLUMNS_ERROR',
  GET_COLUMN_BASIC = 'COLUMN_ACTION/GET_COLUMN_BASIC',
  GET_COLUMN_BASIC_SUCCESS = 'COLUMN_ACTION/GET_COLUMN_BASIC_SUCCESS',
  GET_COLUMN_BASIC_ERROR = 'COLUMN_ACTION/GET_COLUMN_BASIC_ERROR',
  UPDATE_COLUMN_BASIC = 'COLUMN_ACTION/UPDATE_COLUMN_BASIC',
  UPDATE_COLUMN_BASIC_SUCCESS = 'COLUMN_ACTION/UPDATE_COLUMN_BASIC_SUCCESS',
  UPDATE_COLUMN_BASIC_ERROR = 'COLUMN_ACTION/UPDATE_COLUMN_BASIC_ERROR',
  GET_COLUMN_COMMENTS = 'COLUMN_ACTION/GET_COLUMN_COMMENTS',
  GET_COLUMN_COMMENTS_SUCCESS = 'COLUMN_ACTION/GET_COLUMN_COMMENTS_SUCCESS',
  GET_COLUMN_COMMENTS_ERROR = 'COLUMN_ACTION/GET_COLUMN_COMMENTS_ERROR',
  UPDATE_COLUMN_COMMENTS = 'COLUMN_ACTION/UPDATE_COLUMN_COMMENTS',
  UPDATE_COLUMN_COMMENTS_SUCCESS = 'COLUMN_ACTION/UPDATE_COLUMN_COMMENTS_SUCCESS',
  UPDATE_COLUMN_COMMENTS_ERROR = 'COLUMN_ACTION/UPDATE_COLUMN_COMMENTS_ERROR',
  GET_COLUMN_LABELS = 'COLUMN_ACTION/GET_COLUMN_LABELS',
  GET_COLUMN_LABELS_SUCCESS = 'COLUMN_ACTION/GET_COLUMN_LABELS_SUCCESS',
  GET_COLUMN_LABELS_ERROR = 'COLUMN_ACTION/GET_COLUMN_LABELS_ERROR',
  UPDATE_COLUMN_LABELS = 'COLUMN_ACTION/UPDATE_COLUMN_LABELS',
  UPDATE_COLUMN_LABELS_SUCCESS = 'COLUMN_ACTION/UPDATE_COLUMN_LABELS_SUCCESS',
  UPDATE_COLUMN_LABELS_ERROR = 'COLUMN_ACTION/UPDATE_COLUMN_LABELS_ERROR',
  GET_COLUMN_CHECKS_UI = 'COLUMN_ACTION/GET_COLUMN_CHECKS_UI',
  GET_COLUMN_CHECKS_UI_SUCCESS = 'COLUMN_ACTION/GET_COLUMN_CHECKS_UI_SUCCESS',
  GET_COLUMN_CHECKS_UI_ERROR = 'COLUMN_ACTION/GET_COLUMN_CHECKS_UI_ERROR',
  UPDATE_COLUMN_CHECKS_UI = 'COLUMN_ACTION/UPDATE_COLUMN_CHECKS_UI',
  UPDATE_COLUMN_CHECKS_UI_SUCCESS = 'TABLE_ACTION/UPDATE_COLUMN_CHECKS_UI_SUCCESS',
  UPDATE_COLUMN_CHECKS_UI_ERROR = 'TABLE_ACTION/UPDATE_COLUMN_CHECKS_UI_ERROR'
}
