export enum CONNECTION_ACTION {
  GET_CONNECTIONS = 'CONNECTION_ACTION/GET_CONNECTIONS',
  GET_CONNECTIONS_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTIONS_SUCCESS',
  GET_CONNECTIONS_ERROR = 'CONNECTION_ACTION/GET_CONNECTIONS_ERROR',
  SET_ACTIVE_CONNECTION = 'SET_ACTIVE_CONNECTION'
}
