export enum CONNECTION_ACTION {
  GET_CONNECTIONS = 'CONNECTION_ACTION/GET_CONNECTIONS',
  GET_CONNECTIONS_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTIONS_SUCCESS',
  GET_CONNECTIONS_ERROR = 'CONNECTION_ACTION/GET_CONNECTIONS_ERROR',
  SET_ACTIVE_CONNECTION = 'SET_ACTIVE_CONNECTION',
  GET_CONNECTION_BASIC = 'CONNECTION_ACTION/GET_CONNECTION_BASIC',
  GET_CONNECTION_BASIC_SUCCESS = 'CONNECTION_ACTION/GET_CONNECTION_BASIC_SUCCESS',
  GET_CONNECTION_BASIC_ERROR = 'CONNECTION_ACTION/GET_CONNECTION_BASIC_ERROR',
  UPDATE_CONNECTION_BASIC = 'CONNECTION_ACTION/UPDATE_CONNECTION_BASIC',
  UPDATE_CONNECTION_BASIC_SUCCESS = 'CONNECTION_ACTION/UPDATE_CONNECTION_BASIC_SUCCESS',
  UPDATE_CONNECTION_BASIC_ERROR = 'CONNECTION_ACTION/UPDATE_CONNECTION_BASIC_ERROR'
}
