export const checkNameDictionary = {
  daily_row_count_anomaly: 'Row count anomaly',
  daily_row_count: 'Row count',
  daily_partition_row_count_anomaly: 'Partition row count anomaly',
  daily_partition_row_count: 'Partition row count',
  daily_data_freshness_anomaly: 'Table freshness anomaly',
  daily_data_freshness: 'Table freshness',
  daily_nulls_percent_anomaly: 'Null percent anomaly',
  daily_nulls_percent: 'Null percent',
  daily_distinct_count_anomaly: 'Distinct count anomaly',
  daily_distinct_count: 'Distinct count',
  daily_partition_nulls_percent_anomaly: 'Null percent anomaly',
  daily_partition_nulls_percent: 'Null percent',
  daily_partition_distinct_count_anomaly: 'Distinct count anomaly',
  daily_partition_distinct_count: 'Distinct count',
  daily_column_count: 'Expected column count',
  daily_column_count_changed: 'Detect change of column count',
  daily_column_list_changed: 'Detect if columns were added or removed',
  daily_column_list_or_order_changed: 'Detect if column list or order has changed',
  daily_column_types_changed: 'Detect if column list or data type has changed',
  daily_detected_datatype_in_text_changed: 'Detect a change of the data type of all values in a text column',
  daily_column_exists: 'Verify if the column exists',
  daily_column_type_changed: 'Verify if the column data type has changed'
};
