///
/// Copyright © 2021 DQOps (support@dqops.com)
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

export enum CheckTypes {
  MONITORING = 'monitoring',
  SOURCES = 'sources',
  PROFILING = 'profiling',
  PARTITIONED = 'partitioned',
}
export const ROUTES = {
  CONNECTION_DETAIL: (checkTypes: string, connection: string, tab: string) => `/${checkTypes}/connection/${connection}/${tab}`,
  SCHEMA_LEVEL_PAGE: (checkTypes: string, connection: string, schema: string, tab: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/${tab}`,
  TABLE_LEVEL_PAGE: (checkTypes: string, connection: string, schema: string, table: string, tab: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/${tab}`,
  TABLE_PROFILING: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checks/advanced-profiling`,
  TABLE_PROFILING_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checks/advanced-profiling/${category}/${checkName}`,
  TABLE_MONITORING: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/monitoring/${timePartitioned}`,
  TABLE_MONITORING_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/monitoring/${timePartitioned}/${category}/${checkName}`,
  TABLE_PARTITIONED: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/partitioned/${timePartitioned}`,
  TABLE_PARTITIONED_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/partitioned/${timePartitioned}/${category}/${checkName}`,
  TABLE_COLUMNS: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/all`,
  TABLE_INCIDENTS_NOTIFICATION: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/incidents/configuration`,
  COLUMN_LEVEL_PAGE: (checkTypes: string, connection: string, schema: string, table: string, column: string, tab: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/${tab}`,
  COLUMN_PROFILING: (checkTypes: string, connection: string, schema: string, table: string, column: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/advanced-profiling`,
  COLUMN_PROFILING_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, column: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/advanced-profiling/${category}/${checkName}`,
  COLUMN_MONITORING: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/monitoring/${timePartitioned}`,
  COLUMN_MONITORING_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/monitoring/${timePartitioned}/${category}/${checkName}`,
  COLUMN_PARTITIONED: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned/${timePartitioned}`,
  COLUMN_PARTITIONED_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned/${timePartitioned}/${category}/${checkName}`,
  SENSOR_DETAIL: (sensor: string) => `/definitions/sensors/${sensor}`,
  RULE_DETAIL: (rule: string) => `/definitions/rules/${rule}`,
  CHECK_DETAIL: (check: string) => `/definitions/checks/${check}`,
  CHECK_DEFAULT_DETAIL: (defaultCheck: string) => `/definitions/default_checks/${defaultCheck}`,
  INCIDENT_CONNECTION: (name: string) => `/incidents/${name}`,
  INCIDENT_DETAIL: (name: string, year: number, month: number, id: string) => `/incidents/${name}/${year}/${month}/${id}`,
  USERS_LIST_DETAIL: () => '/definitions/users/all',
  USER_DETAIL: (email: string) => `/definitions/user/${email}`,
  SCHEDULES_DEFAULT_DETAIL: () => '/definitions/default-schedules',
  WEBHOOKS_DEFAULT_DETAIL: () => '/definitions/default-webhooks',
  SHARED_CREDENTAILS_LIST_DETAIL: () => '/definitions/shared-credentails',
  SHARED_CREDENTAILS_DETAIL: () => '/definitions/shared-credentail',

  CONNECTION_LEVEL_VALUE: (checkTypes: string, connection: string) => `/${checkTypes}/connection/${connection}`,
  SCHEMA_LEVEL_VALUE: (checkTypes: string, connection: string, schema: string) => `/${checkTypes}/connection/${connection}/schema/${schema}`,
  TABLE_LEVEL_VALUE: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}`,
  TABLE_PROFILING_VALUE: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checks/advanced-profiling`,
  TABLE_MONITORING_VALUE: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/monitoring`,
  TABLE_PARTITIONED_VALUE: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/partitioned`,
  TABLE_COLUMNS_VALUE: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/all`,
  TABLE_INCIDENTS_NOTIFICATION_VALUE: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/incidents/configuration`,
  COLUMN_PROFILING_VALUE: (checkTypes: string, connection: string, schema: string, table: string, column: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/advanced-profiling`,
  COLUMN_MONITORING_VALUE: (checkTypes: string, connection: string, schema: string, table: string, column: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/monitoring`,
  COLUMN_PARTITIONED_VALUE: (checkTypes: string, connection: string, schema: string, table: string, column: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned`,
  COLUMN_LEVEL_VALUE: (checkTypes: string, connection: string, schema: string, table: string, column: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}`,
  SENSOR_DETAIL_VALUE: (sensor: string) => `/definitions/sensors/${sensor}`,
  RULE_DETAIL_VALUE: (rule: string) => `/definitions/rules/${rule}`,
  CHECK_DETAIL_VALUE: (check: string) => `/definitions/checks/${check}`,
  CHECK_DEFAULT_DETAIL_VALUE: (defaultCheck: string) => `/definitions/default_checks/${defaultCheck}`,
  INCIDENT_CONNECTION_VALUE: (name: string) => `/incidents/${name}`,
  INCIDENT_DETAIL_VALUE: (name: string, year: number, month: number, id: string) => `/incidents/${name}/${year}/${month}/${id}`,
  USERS_LIST_DETAIL_VALUE: () => '/definitions/users/all',
  USER_DETAIL_VALUE: (email: string) => `/definitions/user/${email}`,
  SCHEDULES_DEFAULT_DETAIL_VALUE: () => '/definitions/default-schedules',
  WEBHOOKS_DEFAULT_DETAIL_VALUE: () => '/definitions/default-webhooks',
  SHARED_CREDENTAILS_LIST_DETAIL_VALUE: () => '/definitions/shared-credentails',
  SHARED_CREDENTAILS_DETAIL_VALUE: () => '/definitions/shared-credentail',

  PATTERNS: {
    INDEX: '/',
    CONNECTION: '/:checkTypes/connection/:connection/:tab',
    SCHEMA: '/:checkTypes/connection/:connection/schema/:schema/:tab',
    TABLE: '/:checkTypes/connection/:connection/schema/:schema/table/:table/:tab',
    TABLE_PROFILING: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checks/advanced-profiling',
    TABLE_PROFILING_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checks/advanced-profiling/:category/:checkName',
    TABLE_MONITORING_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/monitoring/daily',
    TABLE_MONITORING_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/monitoring/monthly',
    TABLE_MONITORING_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/monitoring/:timePartitioned/:category/:checkName',
    TABLE_PARTITIONED_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/partitioned/daily',
    TABLE_PARTITIONED_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/partitioned/monthly',
    TABLE_PARTITIONED_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/partitioned/:timePartitioned/:category/:checkName',
    TABLE_COLUMNS: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/all',
    TABLE_INCIDENTS_NOTIFICATION: '/:checkTypes/connection/:connection/schema/:schema/table/:table/incidents/configuration',
    COLUMN: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/:tab',
    COLUMN_PROFILING: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checks/advanced-profiling',
    COLUMN_PROFILING_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checks/advanced-profiling/:category/:checkName',
    COLUMN_MONITORING_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/monitoring/daily',
    COLUMN_MONITORING_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/monitoring/monthly',
    COLUMN_MONITORING_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/monitoring/:timePartitioned/:category/:checkName',
    COLUMN_PARTITIONED_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/daily',
    COLUMN_PARTITIONED_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/monthly',
    COLUMN_PARTITIONED_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/:timePartitioned/:category/:checkName',
    QUALITY_CHECKS: '/:checkTypes',
    HOME: '/home',
    DASHBOARDS: '/dashboards',
    CREATE: '/create',
    DEFINITIONS: '/definitions',
    INCIDENTS: '/incidents',
    SENSOR_DETAIL: '/definitions/sensors/:sensor',
    RULE_DETAIL: '/definitions/rules/:rule',
    CHECK_DETAIL: '/definitions/checks/:check',
    CHECK_DEFAULT_DETAIL: '/definitions/default_checks/:defaultCheck',
    INCIDENT_CONNECTION: '/incidents/:connection',
    INCIDENT_DETAIL: '/incidents/:connection/:year/:month/:id',
    USERS_LIST_DETAIL: '/definitions/users/all',
    USER_DETAIL: '/definitions/user/:email',
    SCHEDULES_DEFAULT_DETAIL: '/definitions/default-schedules',
    WEBHOOKS_DEFAULT_DETAIL: '/definitions/default-webhooks',
    SHARED_CREDENTAILS_LIST_DETAIL: '/definitions/shared-credentails',
    SHARED_CREDENTAILS_DETAIL: '/definitions/shared-credentail',
  }
};
