/*
 * Copyright © 2021-Present DQOps, Documati sp. z o.o. (support@dqops.com)
 *
 * This file is licensed under the Business Source License 1.1,
 * which can be found in the root directory of this repository.
 *
 * Change Date: This file will be licensed under the Apache License, Version 2.0,
 * four (4) years from its last modification date.
 */

package com.dqops.services.check.mining;

import com.dqops.metadata.id.HierarchyIdModel;
import com.dqops.metadata.search.CheckSearchFilters;
import com.dqops.services.check.mapping.models.CheckContainerModel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import io.swagger.annotations.ApiModel;
import lombok.Data;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Model that has a proposed configuration of checks on a table and its columns generated by a data quality check mining service.
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@ApiModel(value = "CheckMiningProposalModel", description = "Model that has a proposed configuration of checks on a table and its columns generated by a data quality check mining service.")
public class CheckMiningProposalModel {
    /**
     * A boolean flag to inform the caller that the rule mining engine failed to propose relevant data quality rules because there are no current statistics. The user should schedule a 'collect statistics' job to analyze the table.
     */
    @JsonPropertyDescription("A boolean flag to inform the caller that the rule mining engine failed to propose relevant data quality rules because there are no current statistics. The user should schedule a 'collect statistics' job to analyze the table.")
    private boolean missingCurrentStatistics;

    /**
     * A boolean flag to inform the caller that the rule mining engine failed to propose relevant data quality rules because there are no current results from profiling checks. The user should run profiling checks to analyze the table.
     */
    @JsonPropertyDescription("A boolean flag to inform the caller that the rule mining engine failed to propose relevant data quality rules because there are no current results from profiling checks. The user should run profiling checks to analyze the table.")
    private boolean missingCurrentProfilingCheckResults;

    /**
     * Proposed configuration of table-level data quality checks, such as volume, timeliness or schema.
     */
    @JsonPropertyDescription("Proposed configuration of table-level data quality checks, such as volume, timeliness or schema.")
    private CheckContainerModel tableChecks;

    /**
     * Dictionary of proposed data quality checks for each column.
     */
    @JsonPropertyDescription("Dictionary of proposed data quality checks for each column.")
    private Map<String, CheckContainerModel> columnChecks = new LinkedHashMap<>();

    @JsonPropertyDescription("Configured parameters for the \"check run\" job that should be pushed to the job queue in order run checks for the table.")
    private CheckSearchFilters runChecksJob;

    /**
     * Collects the list of hierarchy ids that identify all proposed checks. It is used to generate a very specific run check job object that will run only proposed checks.
     * @return A list of hierarchy ids that identify proposed checks.
     */
    public List<HierarchyIdModel> collectChecksHierarchyIds() {
        List<HierarchyIdModel> allHierarchyIds = new ArrayList<>();
        if (this.tableChecks != null) {
            allHierarchyIds.addAll(tableChecks.collectConfiguredChecksHierarchyIds());
        }

        for (CheckContainerModel columnChecks : this.columnChecks.values()) {
            allHierarchyIds.addAll(columnChecks.collectConfiguredChecksHierarchyIds());
        }

        return allHierarchyIds;
    }
}
