export enum CheckTypes {
  CHECKS = 'checks',
  SOURCES = 'sources',
  PROFILING = 'profiling',
  TIME_PARTITIONED = 'time-partitioned',
}
export const ROUTES = {
  CONNECTION_DETAIL: (checkTypes: string, connection: string, tab: string) => `/${checkTypes}/connection/${connection}/${tab}`,
  SCHEMA_LEVEL_PAGE: (checkTypes: string, connection: string, schema: string, tab: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/${tab}`,
  TABLE_LEVEL_PAGE: (checkTypes: string, connection: string, schema: string, table: string, tab: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/${tab}`,
  TABLE_PROFILINGS: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checks/ad-hocs`,
  TABLE_PROFILINGS_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checks/ad-hocs/${category}/${checkName}`,
  TABLE_CHECKPOINTS: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checkpoints/${timePartitioned}`,
  TABLE_CHECKPOINTS_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/checkpoints/${timePartitioned}/${category}/${checkName}`,
  TABLE_PARTITIONED: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/partitioned/${timePartitioned}`,
  TABLE_PARTITIONED_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/partitioned/${timePartitioned}/${category}/${checkName}`,
  TABLE_COLUMNS: (checkTypes: string, connection: string, schema: string, table: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/all`,
  COLUMN_LEVEL_PAGE: (checkTypes: string, connection: string, schema: string, table: string, column: string, tab: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/${tab}`,
  COLUMN_PROFILINGS: (checkTypes: string, connection: string, schema: string, table: string, column: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/ad-hocs`,
  COLUMN_PROFILINGS_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, column: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/ad-hocs/${category}/${checkName}`,
  COLUMN_CHECKPOINTS: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checkpoints/${timePartitioned}`,
  COLUMN_CHECKPOINTS_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checkpoints/${timePartitioned}/${category}/${checkName}`,
  COLUMN_PARTITIONED: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned/${timePartitioned}`,
  COLUMN_PARTITIONED_UI_FILTER: (checkTypes: string, connection: string, schema: string, table: string, column: string, timePartitioned: string, category: string, checkName: string) => `/${checkTypes}/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned/${timePartitioned}/${category}/${checkName}`,

  PATTERNS: {
    INDEX: '/',
    CONNECTION: '/:checkTypes/connection/:connection/:tab',
    SCHEMA: '/:checkTypes/connection/:connection/schema/:schema/:tab',
    TABLE: '/:checkTypes/connection/:connection/schema/:schema/table/:table/:tab',
    TABLE_PROFILINGS: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checks/ad-hocs',
    TABLE_PROFILINGS_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checks/ad-hocs/:category/:checkName',
    TABLE_CHECKPOINTS_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checkpoints/daily',
    TABLE_CHECKPOINTS_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checkpoints/monthly',
    TABLE_CHECKPOINTS_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/checkpoints/:timePartitioned/:category/:checkName',
    TABLE_PARTITIONED_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/partitioned/daily',
    TABLE_PARTITIONED_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/partitioned/monthly',
    TABLE_PARTITIONED_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/partitioned/:timePartitioned/:category/:checkName',
    TABLE_COLUMNS: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/all',
    COLUMN: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/:tab',
    COLUMN_PROFILINGS: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checks/ad-hocs',
    COLUMN_PROFILINGS_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checks/ad-hocs/:category/:checkName',
    COLUMN_CHECKPOINTS_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checkpoints/daily',
    COLUMN_CHECKPOINTS_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checkpoints/monthly',
    COLUMN_CHECKPOINTS_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/checkpoints/:timePartitioned/:category/:checkName',
    COLUMN_PARTITIONED_DAILY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/daily',
    COLUMN_PARTITIONED_MONTHLY: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/monthly',
    COLUMN_PARTITIONED_FILTER: '/:checkTypes/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/:timePartitioned/:category/:checkName',
    QUALITY_CHECKS: '/:checkTypes',
    HOME: '/home',
    DASHBOARDS: '/dashboards',
    CREATE: '/create'
  }
};
