export enum CheckTypes {
  ADHOC = 'data-quality-checks',
  CHECKPOINT = 'checkpoints',
  PARTITION = 'partitioned-checks'
}
export const ROUTES = {
  CONNECTION_DETAIL: (connection: string, tab: string) => `/checks/connection/${connection}/${tab}`,
  SCHEMA_LEVEL_PAGE: (connection: string, schema: string, tab: string) => `/checks/connection/${connection}/schema/${schema}/${tab}`,
  TABLE_LEVEL_PAGE: (connection: string, schema: string, table: string, tab: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/${tab}`,
  TABLE_AD_HOCS: (connection: string, schema: string, table: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/checks/ad-hocs`,
  TABLE_AD_HOCS_UI_FILTER: (connection: string, schema: string, table: string, category: string, checkName: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/checks/ad-hocs/${category}/${checkName}`,
  TABLE_CHECKPOINTS: (connection: string, schema: string, table: string, timePartitioned: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/checkpoints/${timePartitioned}`,
  TABLE_CHECKPOINTS_UI_FILTER: (connection: string, schema: string, table: string, timePartitioned: string, category: string, checkName: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/checkpoints/${timePartitioned}/${category}/${checkName}`,
  TABLE_PARTITIONED: (connection: string, schema: string, table: string, timePartitioned: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/partitioned/${timePartitioned}`,
  TABLE_PARTITIONED_UI_FILTER: (connection: string, schema: string, table: string, timePartitioned: string, category: string, checkName: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/partitioned/${timePartitioned}/${category}/${checkName}`,
  TABLE_COLUMNS: (connection: string, schema: string, table: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/all`,
  COLUMN_LEVEL_PAGE: (connection: string, schema: string, table: string, column: string, tab: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/${tab}`,
  COLUMN_AD_HOCS: (connection: string, schema: string, table: string, column: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/ad-hocs`,
  COLUMN_AD_HOCS_UI_FILTER: (connection: string, schema: string, table: string, column: string, category: string, checkName: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checks/ad-hocs/${category}/${checkName}`,
  COLUMN_CHECKPOINTS: (connection: string, schema: string, table: string, column: string, timePartitioned: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checkpoints/${timePartitioned}`,
  COLUMN_CHECKPOINTS_UI_FILTER: (connection: string, schema: string, table: string, column: string, timePartitioned: string, category: string, checkName: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/checkpoints/${timePartitioned}/${category}/${checkName}`,
  COLUMN_PARTITIONED: (connection: string, schema: string, table: string, column: string, timePartitioned: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned/${timePartitioned}`,
  COLUMN_PARTITIONED_UI_FILTER: (connection: string, schema: string, table: string, column: string, timePartitioned: string, category: string, checkName: string) => `/checks/connection/${connection}/schema/${schema}/table/${table}/columns/${column}/partitioned/${timePartitioned}/${category}/${checkName}`,

  PATTERNS: {
    INDEX: '/',
    CONNECTION: '/checks/connection/:connection/:tab',
    SCHEMA: '/checks/connection/:connection/schema/:schema/:tab',
    TABLE: '/checks/connection/:connection/schema/:schema/table/:table/:tab',
    TABLE_AD_HOCS: '/checks/connection/:connection/schema/:schema/table/:table/checks/ad-hocs',
    TABLE_AD_HOCS_FILTER: '/checks/connection/:connection/schema/:schema/table/:table/checks/ad-hocs/:category/:checkName',
    TABLE_CHECKPOINTS_DAILY: '/checks/connection/:connection/schema/:schema/table/:table/checkpoints/daily',
    TABLE_CHECKPOINTS_MONTHLY: '/checks/connection/:connection/schema/:schema/table/:table/checkpoints/monthly',
    TABLE_CHECKPOINTS_FILTER: '/checks/connection/:connection/schema/:schema/table/:table/checkpoints/:timePartitioned/:category/:checkName',
    TABLE_PARTITIONED_DAILY: '/checks/connection/:connection/schema/:schema/table/:table/partitioned/daily',
    TABLE_PARTITIONED_MONTHLY: '/checks/connection/:connection/schema/:schema/table/:table/partitioned/monthly',
    TABLE_PARTITIONED_FILTER: '/checks/connection/:connection/schema/:schema/table/:table/partitioned/:timePartitioned/:category/:checkName',
    TABLE_COLUMNS: '/checks/connection/:connection/schema/:schema/table/:table/columns/all',
    COLUMN: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/:tab',
    COLUMN_AD_HOCS: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/checks/ad-hocs',
    COLUMN_AD_HOCS_FILTER: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/checks/ad-hocs/:category/:checkName',
    COLUMN_CHECKPOINTS_DAILY: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/checkpoints/daily',
    COLUMN_CHECKPOINTS_MONTHLY: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/checkpoints/monthly',
    COLUMN_CHECKPOINTS_FILTER: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/checkpoints/:timePartitioned/:category/:checkName',
    COLUMN_PARTITIONED_DAILY: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/daily',
    COLUMN_PARTITIONED_MONTHLY: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/monthly',
    COLUMN_PARTITIONED_FILTER: '/checks/connection/:connection/schema/:schema/table/:table/columns/:column/partitioned/:timePartitioned/:category/:checkName',
    CHECKS: '/checks',
    HOME: '/home',
    DASHBOARDS: '/dashboards',
    CREATE: '/create'
  }
};
