from enum import Enum


class DqoJobType(str, Enum):
    COLLECT_STATISTICS = "COLLECT_STATISTICS"
    COLLECT_STATISTICS_ON_TABLE = "COLLECT_STATISTICS_ON_TABLE"
    DELETE_STORED_DATA = "DELETE_STORED_DATA"
    IMPORT_SCHEMA = "IMPORT_SCHEMA"
    IMPORT_TABLES = "IMPORT_TABLES"
    QUEUE_THREAD_SHUTDOWN = "QUEUE_THREAD_SHUTDOWN"
    REPAIR_STORED_DATA = "REPAIR_STORED_DATA"
    RUN_CHECKS = "RUN_CHECKS"
    RUN_CHECKS_ON_TABLE = "RUN_CHECKS_ON_TABLE"
    RUN_SCHEDULED_CHECKS_CRON = "RUN_SCHEDULED_CHECKS_CRON"
    SYNCHRONIZE_FOLDER = "SYNCHRONIZE_FOLDER"
    SYNCHRONIZE_MULTIPLE_FOLDERS = "SYNCHRONIZE_MULTIPLE_FOLDERS"

    def __str__(self) -> str:
        return str(self.value)
